version: "3"
services:
  flask:
    build: ./Flask
    expose: 
      - 5000
    deploy:
      replicas: 3
  nginx:
    image: nginx
    ports:
      - 80:443 
      - 5000:443               
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf/:ro
      - ./nginx-selfsigned.crt:/etc/nginx/nginx-selfsigned.crt 
      - ./nginx-selfsigned.key:/etc/nginx/nginx-selfsigned.key 
    depends_on:
      - flask                